name: Bug report
description: Report a problem
title: "[Bug] "
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: What happened?
      description: Describe the issue and what you expected to happen.
    validations:
      required: true
